name: KeepAlive 

on:
  schedule:
    - cron: "*/10 * * * *"    
    - cron: "7-59/15 * * * *" 
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Jitter (sleep up to 9 minutes)
        run: |
          S=$((RANDOM % 540)) # 0..539 sec
          echo "Sleeping ${S}s..."
          sleep $S

      - name: Ping Render with random path, UA, and cache-buster
        env:
          BASE_URL: ${{ secrets.RENDER_URL }} 
        run: |
          
          PATHS=("/healthz" "/" "/version")
          P=${PATHS[$RANDOM % ${#PATHS[@]}]}

          UAS=("GH-Actions" "curl/7" "Mozilla/5.0 keepalive")
          UA=${UAS[$RANDOM % ${#UAS[@]}]}

          TS=$(date +%s)
          R=$RANDOM

          curl -A "$UA" -fsSL "$BASE_URL$P?src=gha&t=$TS&r=$R" || true


