name: Keep Alive

on:
  schedule:
    - cron: "*/17 * * * *"   # every 15 minutes
  workflow_dispatch:         # allow manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call health endpoint
        run: |
          curl -s -o /dev/null https://lesson-planner-app.onreander.com/health